server:
  port: 9998
  servlet:
    context-path: /

spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 33
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      
  activiti:
    database-schema-update: true
    process-definition-location-prefix: classpath:/processes/